In [2]:
import torch

In [3]:
torch.arange(12)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
torch.arange(12).reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
torch.arange(12).reshape(3,4).shape

torch.Size([3, 4])

In [7]:
torch.arange(12).reshape(3,4).numel()

12

In [8]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.randn(3,4)

tensor([[-0.3049, -1.0018, -2.0065,  1.5151],
        [ 0.3647,  1.4688, -2.1760,  0.2869],
        [-0.4405,  0.1283, -0.9835,  0.9888]])

In [12]:
torch.rand?

In [15]:
x = torch.tensor([1,2,4,8])
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [16]:
x = torch.arange(12, dtype = torch.float32).reshape(3,4)
Y = torch.ones([3,4])

In [18]:
torch.cat((x,Y), dim =0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.]])

In [19]:
torch.cat((x,Y), dim = 1)

tensor([[ 0.,  1.,  2.,  3.,  1.,  1.,  1.,  1.],
        [ 4.,  5.,  6.,  7.,  1.,  1.,  1.,  1.],
        [ 8.,  9., 10., 11.,  1.,  1.,  1.,  1.]])

In [33]:
x< Y

tensor([[ True, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [23]:
x.sum(dim = 0)

tensor([12., 15., 18., 21.])

In [24]:
x.sum(dim = 1)

tensor([ 6., 22., 38.])

In [25]:
z = torch.zeros_like(x)
print(id(z))

1372085779888


In [26]:
z[:] = x + Y
print(id(z))

1372085779888


In [27]:
A = x.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [30]:
a = torch.tensor([3.5])

In [32]:
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [34]:
torch.tensor(3.5), torch.tensor([3.5])

(tensor(3.5000), tensor([3.5000]))

In [35]:
x = torch.tensor(3.5)
x + x, x*x , x/x, x**x

(tensor(7.), tensor(12.2500), tensor(1.), tensor(80.2118))

In [36]:
x = torch.tensor([3.5])
x + x, x*x , x/x, x**x

(tensor([7.]), tensor([12.2500]), tensor([1.]), tensor([80.2118]))

In [38]:
y = torch.arange(12)
len(y)

12

In [39]:
y[10]

tensor(10)

In [41]:
torch.arange(20, dtype = torch.float32).reshape(5,4)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [42]:
a = 2
x = torch.arange(24).reshape(2,3,4)
a +x , a*x

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]))

In [43]:
x

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [48]:
x.shape

torch.Size([2, 3, 4])

In [47]:
x.sum(dim=2)

tensor([[ 6, 22, 38],
        [54, 70, 86]])

In [49]:
x.sum(axis = 0)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [50]:
x.sum()

tensor(276)

In [51]:
x.sum(axis = [0,1,2])

tensor(276)

In [53]:
x = torch.arange(20, dtype = torch.float32).reshape(5,4)
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [54]:
x.sum() / x.numel()

tensor(9.5000)

In [55]:
x.mean()

tensor(9.5000)

In [56]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [57]:
x.mean(axis = 0)

tensor([ 8.,  9., 10., 11.])

In [58]:
x.sum(axis = 0, keepdims = True)

tensor([[40., 45., 50., 55.]])

In [61]:
x.sum(axis = 1, keepdims = True)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [60]:
x / x.sum(axis = 1, keepdims = True)

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [62]:
y  = torch.ones(4, dtype = torch.float32)
torch.dot(y, y)

tensor(4.)

In [63]:
torch.sum(y*y)

tensor(4.)

In [64]:
y*y

tensor([1., 1., 1., 1.])

In [65]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [66]:
y

tensor([1., 1., 1., 1.])

In [67]:
torch.mv(x,y)

tensor([ 6., 22., 38., 54., 70.])

In [69]:
torch.mm(x,x.T)

tensor([[  14.,   38.,   62.,   86.,  110.],
        [  38.,  126.,  214.,  302.,  390.],
        [  62.,  214.,  366.,  518.,  670.],
        [  86.,  302.,  518.,  734.,  950.],
        [ 110.,  390.,  670.,  950., 1230.]])

In [70]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [71]:
torch.abs(u).sum()

tensor(7.)

In [72]:
torch.norm(torch.ones(4,9))

tensor(6.)

In [74]:
x = torch.arange(12, dtype = torch.float32, requires_grad = True)

In [75]:
y = 2* torch.dot(x, x)

In [76]:
y

tensor(1012., grad_fn=<MulBackward0>)

In [77]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44.])

In [79]:
x.grad == 4*x

tensor([True, True, True, True, True, True, True, True, True, True, True, True])

In [81]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [82]:
y = x.sum()

In [83]:
y.backward()

In [84]:
x.grad

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [86]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
y = x*x

In [89]:
y

tensor([  0.,   1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100., 121.],
       grad_fn=<MulBackward0>)

In [90]:
y.sum().backward()
x.grad

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22.])

In [91]:
x.grad.zero_()

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [92]:
y = x*x
u = y.detach()
z = u*x

z.sum().backward()
x.grad == u

tensor([True, True, True, True, True, True, True, True, True, True, True, True])

In [93]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True, True, True, True, True, True, True, True, True])

In [94]:
b = torch.rand(2)

In [96]:
b.norm()

tensor(0.7716)

In [97]:
from torch.distributions import multinomial

In [98]:
fair_probs = torch.ones([6]) / 6

In [99]:
fair_probs

tensor([0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667])

In [100]:
multinomial.Multinomial(1, fair_probs).sample()

tensor([0., 0., 1., 0., 0., 0.])